export const sampleComments = [
  "Привет - Hello",
  "Спасибо - Thank you",
  "Пожалуйста - Please",
  "До свидания - Goodbye",
  "Как дела? - How are you?",
  "Я в порядке - I'm fine",
  "Где...? - Where is...?",
  "Сколько стоит? - How much does it cost?",
  "Я не понимаю - I don't understand",
  "Говорите медленнее - Speak slower",
  "Я из... - I'm from...",
  "Меня зовут... - My name is...",
  "Я студент - I'm a student",
  "Я работаю - I work",
  "Я люблю... - I like...",
  "Мне нравится... - I enjoy...",
  "Я устал - I'm tired",
  "Я голоден - I'm hungry",
  "Вода - Water",
  "Хлеб - Bread",
  "Пиво - Beer",
  "Вино - Wine",
  "Хорошо - Good",
  "Плохо - Bad",
  "Сейчас - Now",
  "Скоро - Soon",
  "Уже - Already",
  "Ещё - Still",
  "Завтра - Tomorrow",
  "Вчера - Yesterday",
  "Сегодня - Today",
  "Россия - Russia",
  "Москва - Moscow",
  "Санкт-Петербург - St. Petersburg",
  "Я люблю Россию - I love Russia",
  "Мне нравится русский язык - I like the Russian language",
  "Иди сюда - Come here",
  "Господин - Mister",
  "Госпожа - Missus",
  "Простите - Excuse me",
];

export const commentColors = [
  "#FFFFFF",
  "#FF6B6B",
  "#4ECDC4",
  "#45B7D1",
  "#96CEB4",
  "#FFEAA7",
  "#DDA0DD",
  "#98D8C8",
  "#F7DC6F",
  "#BB8FCE",
  "#85C1E9",
  "#F8C471",
  "#82E0AA",
  "#F1948A",
];
