export const sampleComments = [
  "yo - i",
  "tú - you",
  "él/ella/usted - he/she/you (formal)",
  "nosotros/as - we",
  "vosotros/as - you (plural, informal)",
  "ellos/as - they",
  "ser - to be (permanent)",
  "estar - to be (temporary)",
  "hablar - to speak",
  "venir - to come",
  "ir - to go",
  "tomar - to take",
  "dormir - to sleep",
  "comer - to eat",
  "beber - to drink",
  "leer - to read",
  "escuchar - to listen",
  "mirar - to look",
  "decir - to say",
  "hola - hello",
  "adiós - goodbye",
  "gracias - thank you",
  "por favor - please",
  "lo siento - sorry",
  "¿cómo estás? - how are you?",
  "estoy bien - i'm fine",
  "¿dónde está...? - where is...?",
  "¿cuánto cuesta? - how much does it cost?",
  "¿habla inglés? - do you speak english?",
  "¿entiendo - i don't understand",
  "¿dónde está el baño? - where is the bathroom?",
  "me llamo - my name is",
  "soy de - i'm from",
  "¿qué hora es? - what time is it?",
  "hoy - today",
  "mañana - tomorrow",
  "ayer - yesterday",
  "¿quién? - who?",
  "¿qué? - what?",
];

export const commentColors = [
  "#FFFFFF",
  "#FF6B6B",
  "#4ECDC4",
  "#45B7D1",
  "#96CEB4",
  "#FFEAA7",
  "#DDA0DD",
  "#98D8C8",
  "#F7DC6F",
  "#BB8FCE",
  "#85C1E9",
  "#F8C471",
  "#82E0AA",
  "#F1948A",
];
